name: saltstack-repos-formula
source: https://github.com/bechtoldt/saltstack-repos-formula
summary: SaltStack formula to set up and configure software repositories, e.g. APT or YUM
todo:
  - add instructions how to use formhelper, add information about it in the formula-docs (dependency), show up alternative?
  - 'table/ matrix: os/salt compatibility (dedicated file)'
  - add list of available states
  - add tests
